services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgres://allocationsystem_user:bCFBDoTHhG1mrNfAGqlSVNiO58YbYPe8@dpg-cp6gfjfsc6pc73fufgag-a.ohio-postgres.render.com/allocationsystem
      - key: SECRET_KEY
        value: teByORjL8jsS_HccRh_n08bwPio
